plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-cs24.github.io/f23 
baseurl: "/f23"  
instructor: "Diba Mirza"
name: "CS24 Fall 2023"
course: "CS24"
course_title: "Problem Solving with Computers II"
title: "UCSB CS24 F23"
github_url: https://github.com/ucsb-cs24/f23
qtr: "F23"
quarter: "Fall 2023"
lecture_times: "MW 12:30pm - 1:45pm"
lecture_location: "TD-W 1701"
lab_times: "Thursdays: 10a, 11a, 1p"
tas: "Mehak Dhaliwal, Sherry Chen, Jeffrey Chen"
ulas: "Zack Glazewski, Karanina Zim, Torin Schlunk"
class_org:
   name: ucsb-cs24-f23
   url: https://github.com/ucsb-cs24-f23
   githublinker: CS24 F23
   
lect_repo: https://github.com/ucsb-cs24-f23/cs24-f23-lectures
start_week: 1
start_date: 2023-10-01
num_weeks: 10
extra_exam_week: true

instructor_url: https://ucsb-cs24.github.io/instructor

cal_dates: >
  [
  {"label":"First day of classes", "date":"2023-10-02" },
  {"label":"Drop deadline (no W grade)","date":"2023-10-25" },
  {"label":"Thanksgiving - No lecture", "date":"2023-11-22" },
  {"label":"F23 Instruction Ends", "date":"2023-12-08" },  
  {"label":"F23 Quarter Ends", "date":"2023-12-15" }          
  ]

kramdown:
   parse_block_html: true

exclude:
   - vendor
include:
  - _pages

timezone: America/Los_Angeles

collections:
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  pa:
    output: true
    permalink: /pa/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  -
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  -
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  -
    scope:
      path: ""
      type: pa
    values:
      layout: lab
  -
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  -
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout

theme: jekyll-theme-cayman
